### ISSUE TITLE
Rename process.id to process.name

### ISSUE THREAD

**Issue by dmitri-carpov** [ypg-data/eigenflow#11]
Currently `ProcessType`, `Process` are used and the `processId` field in events messages conflicts with `process.id` in configuration. Need a more consistent language.

**Comment by suhailshergill** [comment]
@dmitri-carpov could you link to what this is a `duplicate` of?

**Comment by dmitri-carpov** [comment]
@suhailshergill #10 and #24 are covering this issue much wider
