### ISSUE TITLE
Generic Messages Support

### ISSUE THREAD

**Issue by dmitri-carpov** [ypg-data/eigenflow#15]
**Motivation**
Allow to send `String` type messages to `eigenflow` message queue

**Input**
Current implementation which allows to send only metrics messages (Map[String, Double])

**Output**
- DSL or `function` for sending a generic (String type) messages
- Documentation how to use it

**Test**
- Review unit tests.
- Check documentation
- Test functionality using a `testjob`

**Comment by suhailshergill** [comment]
@dmitri-carpov in the solutions i would like one which would be extensible, should we need to extend in the future
