### ISSUE TITLE
Process stages can't serialise `(): Unit`

### ISSUE THREAD

**Issue by yawaramin** [ypg-data/eigenflow#5]
Process stages can't serialise the `(): Unit` value. E.g. if we have

``` scala
case object Test extends ProcessStage
val test = Test { _: String => Future(()) }
```

We get an error:

```
No implicit view available from Unit => String.
```

Solution: add the suggested implicit view?

**Comment by dmitri-carpov** [comment]
Fixed in https://github.com/ypg-data/eigenflow/commit/a79a6ca944be6a131d57fd4585b4a300096cb933

see `src/main/scala/com.mediative.eigenflow/helpers/PrimitiveImplicits.scala`
